# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesafe < Formula
  desc "Safely manage multiple Kubernetes clusters by defining safe contexts and protected commands."
  homepage "https://github.com/Telemaco019/kubesafe"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Darwin_x86_64.tar.gz"
      sha256 "0276b9851b088a478901d5517c011483bef4931e53e15a1986fb1462bd07c4a9"

      def install
        bin.install "kubesafe"
      end
    end
    on_arm do
      url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Darwin_arm64.tar.gz"
      sha256 "133deb1c797326595dd6c738fc2ee0609a9231b82f9d9f55e3c7cee95ebb06c4"

      def install
        bin.install "kubesafe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Linux_x86_64.tar.gz"
        sha256 "c98abaf5b9f12e933d9bf25883805fb65922ee85bbe31cb4da15321181d409d8"

        def install
          bin.install "kubesafe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Linux_arm64.tar.gz"
        sha256 "0022301b57a9736e7a3dddbd07f34be742463398ff70b514841b5ea5fc3c6591"

        def install
          bin.install "kubesafe"
        end
      end
    end
  end
end
