# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesafe < Formula
  desc "Safely manage multiple Kubernetes clusters by defining safe contexts and protected commands."
  homepage "https://github.com/Telemaco019/kubesafe"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Darwin_x86_64.tar.gz"
      sha256 "96c27e0653ff409ed0c2673edb1689d180535f317047efda4ff7686f90c43762"

      def install
        bin.install "kubesafe"
      end
    end
    on_arm do
      url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Darwin_arm64.tar.gz"
      sha256 "c5aa480d01325e1f48c7ec711e7d331f9233b607fdc5d78efe4304c1144f83b1"

      def install
        bin.install "kubesafe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Linux_x86_64.tar.gz"
        sha256 "c637130538cb2783baa83a9524d82e77a685cac0719a7ac0f26001832409b231"

        def install
          bin.install "kubesafe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/kubesafe/releases/download/v0.1.0/kubesafe_Linux_arm64.tar.gz"
        sha256 "35abc04208e4426c928848a210aef0157fd25c9499d94e0d209781cde7feacf9"

        def install
          bin.install "kubesafe"
        end
      end
    end
  end
end
